language: objective-c
cache:
  directories:
    - vendor/bundle
install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
script:
  - bundle exec rake test:ios test:osx coverage:coveralls
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
